// supplements that are not generated by BTF of vmlinux

struct bpf_map_def {
	unsigned int type;
	unsigned int key_size;
	unsigned int value_size;
	unsigned int max_entries;
	unsigned int map_flags;
};

// include some headers in system default path
#include <linux/if_ether.h> // for ETH_P_* macro constants
#include <linux/filter.h> // for BPF_* macro constants
#include <linux/bpf.h> // for BPF_* macro constants
#include <linux/in6.h> // for IPPROTO_* macro constants
#include <sys/socket.h>  // for AF_*, SOCK_* macro constants
#include <linux/if_ether.h>  // for ETH_* macro constants
