name: Rust

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu:latest', 'ubuntu:rolling']

    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@2.0.0
      
    - name: Add LLVM 9 packages
      run: |
        apt-get update && apt-get install -y curl gnupg2 software-properties-common lsb-release git
        curl https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
        add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'

    - name: Install necessary packages
      run: |
        apt-get install -y clang llvm-9 libelf-dev ca-certificates{,-java} linux-headers-$(uname -r)
        echo "export KERNEL_VERSION=$(uname -r)" >> ${HOME}/.bashrc
        curl --proto '=https' --tlsv1.2 -sSf -o rustup.sh https://sh.rustup.rs

        chmod 755 rustup.sh
        ./rustup.sh -y
        . /root/.cargo/env
        cat /root/.cargo/env >> $BASH_ENV
        rustup default nightly
        rustup target add x86_64-unknown-linux-musl
        rustup component add rustfmt
      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --bins --tests --verbose
    - name: Build docs
      run: cargo doc --no-deps
