name: Rust

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu:latest', 'ubuntu:rolling']

    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@2.0.0
      
    - name: Add LLVM 9 packages
      run: |
          curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9  main'

    - name: Install necessary packages
      run: |
          sudo apt-get install -y clang llvm-9 libelf-dev ca-certificates{,-java} linux-headers-$(uname -r)
          echo "export KERNEL_VERSION=$(uname -r)" >> ${HOME}/.bashrc
      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --bins --tests --verbose
    - name: Build docs
      run: cargo doc --no-deps
